/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.klijent.PretragaKlijenta;
import forms.klijent.UnosKlijenta;
import forms.trening.Stavke;
import forms.trening.UnesiStavku;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author user
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        lblTrener.setText("Logged: " + Session.getInstance().getCurrentUser().getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTrener = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiUnesiKlijenta = new javax.swing.JMenuItem();
        jmiBrisanjeKlijenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiUnosStavke = new javax.swing.JMenuItem();
        jmiStavke = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTrener.setText("jLabel1");

        jMenu1.setText("Klijent");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmiUnesiKlijenta.setText("Novi Klijent");
        jmiUnesiKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnesiKlijentaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUnesiKlijenta);

        jmiBrisanjeKlijenta.setText("Brisanje I Pretraga");
        jmiBrisanjeKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBrisanjeKlijentaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBrisanjeKlijenta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Trening");

        jmiUnosStavke.setText("Rezim");
        jmiUnosStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosStavkeActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUnosStavke);

        jmiStavke.setText("Stavke");
        jmiStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStavkeActionPerformed(evt);
            }
        });
        jMenu2.add(jmiStavke);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(lblTrener)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(lblTrener)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmiUnesiKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnesiKlijentaActionPerformed
         JDialog d = new UnosKlijenta(this, true);
         prikaziFormu(d);
        
    }//GEN-LAST:event_jmiUnesiKlijentaActionPerformed

    private void jmiBrisanjeKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBrisanjeKlijentaActionPerformed
       JDialog d = new PretragaKlijenta(this, true,FormMode.OBRISI);
        prikaziFormu(d);
    }//GEN-LAST:event_jmiBrisanjeKlijentaActionPerformed

    private void jmiUnosStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosStavkeActionPerformed
        UnesiStavku f = new UnesiStavku(this, true);
        prikaziFormu(f);
    }//GEN-LAST:event_jmiUnosStavkeActionPerformed

    private void jmiStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStavkeActionPerformed
        Stavke st = new Stavke(this, true);
        prikaziFormu(st);
    }//GEN-LAST:event_jmiStavkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiBrisanjeKlijenta;
    private javax.swing.JMenuItem jmiStavke;
    private javax.swing.JMenuItem jmiUnesiKlijenta;
    private javax.swing.JMenuItem jmiUnosStavke;
    private javax.swing.JLabel lblTrener;
    // End of variables declaration//GEN-END:variables

    private void prikaziFormu(JDialog d) {
        if (Session.getInstance().isOtvoriFormu()) {
            d.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Server pao!");
            System.exit(0);
        }
    }
}
