/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.klijent;

import domain.Klijent;
import domain.RezimTreninga;
import domain.StavkaRezimaTreninga;
import forms.FormMode;
import forms.models.TableModelKlijent;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logics.Controler;
import session.Session;

/**
 *
 * @author user
 */
public class PretragaKlijenta extends javax.swing.JDialog {
    
    
    /**
     * Creates new form PretragaKlijenta
     */
    public PretragaKlijenta(java.awt.Frame parent, boolean modal, FormMode mode) {
        super(parent, modal);
        Session.getInstance().setOtvoriFormu(true);
        initComponents();
        populateTable();
        cbVrste.removeAllItems();
        btnObrisi.setEnabled(false);
        setujFormu(mode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlijent = new javax.swing.JTable();
        btnObrisi = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        cbVrste = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIme1 = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        txtJmbg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime");

        tblKlijent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlijent);

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnPrikazi.setText("Prikazi");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        cbVrste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Ime");

        jLabel3.setText("Prezime");

        jLabel4.setText("Kontakt");

        jLabel5.setText("JMBG");

        jLabel6.setText("Vrsta Treninga");

        txtKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKontaktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPretrazi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrikazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisi)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIme1)
                    .addComponent(txtPrezime)
                    .addComponent(txtKontakt)
                    .addComponent(txtJmbg)
                    .addComponent(cbVrste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnPretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikazi)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbVrste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int r = tblKlijent.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da nađe klijenta po zadatoj vrednosti! Morate selektovati klijenta!");
            return;
        }
        TableModelKlijent tmp = (TableModelKlijent) tblKlijent.getModel();
        Klijent v = tmp.getKorisnici().get(r);
        try {
            Controler.getInstance().obrisiKlijenta(v.getKlijentId());
            JOptionPane.showMessageDialog(null, "Sistem je obrisao klijenta!");
            populateTable();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da obriše klijenta!");
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da obriše klijenta!");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String ime = txtIme.getText();
        if(ime.isEmpty()){
            populateTable();
            return;
        }
        ArrayList<Klijent> mojiK = new ArrayList<>();
        TableModelKlijent tmk = (TableModelKlijent) tblKlijent.getModel();
        ArrayList<Klijent> ukupni = tmk.getKorisnici();
        for (Klijent klijent : ukupni) {
            if(klijent.getIme().toLowerCase().contains(ime)){
                mojiK.add(klijent);
            }
        }
        tmk.setKorisnici(mojiK);
        tmk.fireTableDataChanged();
        tblKlijent.setModel(tmk);
        
        
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int r = tblKlijent.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da nađe klijenta po zadatoj vrednosti! Morate selektovati stavku!");
            return;
        }
        TableModelKlijent tmp = (TableModelKlijent) tblKlijent.getModel();
        Klijent k = tmp.getKorisnici().get(r);
        cbVrste.removeAllItems();
        cbVrste.addItem(k.getVrstaTreninga().getNazivVrsteTreninga());
        cbVrste.setEnabled(false);
        
        txtIme1.setText(k.getIme());
        txtPrezime.setText(k.getPrezime());
        txtJmbg.setText(k.getJmbg());
        txtKontakt.setText(k.getKontakt());
        
        txtIme1.setEnabled(false);
        txtPrezime.setEnabled(false);
        txtJmbg.setEnabled(false);
        txtKontakt.setEnabled(false);
        
        
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void txtKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontaktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontaktActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               /* PretragaKlijenta dialog = new PretragaKlijenta(new javax.swing.JFrame(), true, FormMode.DODAJ);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<Object> cbVrste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlijent;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtIme1;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        try {
            ArrayList<Klijent> stavke = Controler.getInstance().vratiKlijente();
            TableModelKlijent tmp = new TableModelKlijent(stavke);
            tblKlijent.setModel(tmp);
        } catch (Exception ex) {
            Session.getInstance().setOtvoriFormu(false);
            JOptionPane.showMessageDialog(null, "Sistem ne može da vrati klijente!");
            this.dispose();
        }}

    private void setujFormu(FormMode mode) {
        if (mode == FormMode.OBRISI) {
            btnObrisi.setEnabled(true);
            
        }
    }
}
