/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.klijent;

import domain.Klijent;
import domain.VrstaTreninga;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logics.Controler;
import session.Session;

/**
 *
 * @author user
 */
public class UnosKlijenta extends javax.swing.JDialog {

    /**
     * Creates new form UnosKlijenta
     */
    
    Klijent k = new Klijent();
    ArrayList<VrstaTreninga> vrste = new ArrayList<>();
    
    public UnosKlijenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        Session.getInstance().setOtvoriFormu(true);
        initComponents();
        prepareCb();
    }
    
    public UnosKlijenta(java.awt.Frame parent, boolean modal,Klijent k) {
        super(parent, modal);
        Session.getInstance().setOtvoriFormu(true);
        initComponents();
        prikaziKlijenta(k);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        txtJmbg = new javax.swing.JTextField();
        cbVrste = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos ");

        btnUnos.setText("Unesi Klijenta");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("Kontakt");

        jLabel4.setText("JMBG");

        jLabel5.setText("Vrsta Treninga");

        txtKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKontaktActionPerformed(evt);
            }
        });

        cbVrste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUnos, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIme)
                            .addComponent(txtPrezime)
                            .addComponent(txtKontakt)
                            .addComponent(txtJmbg)
                            .addComponent(cbVrste, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbVrste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnUnos)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontaktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontaktActionPerformed

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
        if(!setujKlijenta()) {
            return;
        }

        try {
            Controler.getInstance().sacuvajKlijenta(k);
            JOptionPane.showMessageDialog(null, "Sistem je zapamtio klijenta.");

            Object[] options = {"Da", "Ne"};

            if (JOptionPane.showOptionDialog(null, "Da li zelite da unesete novog klijenta?", "Novi klijent",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, options, options[0]) == 0) {
                UnosKlijenta lup = new UnosKlijenta(null, true);
                this.dispose();
                lup.setVisible(true);
            } else {
                this.dispose();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da zapamti klijenta.");
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da zapamti klijenta.");
        }
    }//GEN-LAST:event_btnUnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnosKlijenta dialog = new UnosKlijenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnos;
    private javax.swing.JComboBox<Object> cbVrste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void prepareCb() {
        cbVrste.removeAllItems();
        try {
            ArrayList<VrstaTreninga> vrste = Controler.getInstance().vratiVrste();
            for (VrstaTreninga vrstaTreninga : vrste) {
                cbVrste.addItem(vrstaTreninga);
            }
        } catch (Exception ex) {
            Logger.getLogger(UnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private boolean setujKlijenta() {
        if (
                txtIme.getText().isEmpty() ||
                txtPrezime.getText().isEmpty() ||
                txtKontakt.getText().isEmpty() ||
                txtJmbg.getText().isEmpty()
                
        ) {
            JOptionPane.showMessageDialog(null, "Popunite sva polja!");
            return false;
        }
        k = new Klijent(0, txtIme.getText(), txtPrezime.getText(), txtJmbg.getText(), txtKontakt.getText(), (VrstaTreninga) cbVrste.getSelectedItem());
        
        return true;
    }

    private void prikaziKlijenta(Klijent k) {
        cbVrste.removeAllItems();
        cbVrste.addItem(k.getVrstaTreninga().getNazivVrsteTreninga());
        cbVrste.setEnabled(false);
        
        txtIme.setText(k.getIme());
        txtPrezime.setText(k.getPrezime());
        txtJmbg.setText(k.getJmbg());
        txtKontakt.setText(k.getKontakt());
        
        txtIme.setEnabled(false);
        txtPrezime.setEnabled(false);
        txtJmbg.setEnabled(false);
        txtKontakt.setEnabled(false);
        btnUnos.setEnabled(false);
    }
}
