/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.trening;

import domain.RezimTreninga;
import domain.StavkaRezimaTreninga;
import domain.VrstaTreninga;
import forms.klijent.UnosKlijenta;
import forms.models.TableModelStavke;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logics.Controler;
import session.Session;

/**
 *
 * @author user
 */
public class UnesiStavku extends javax.swing.JDialog {
    RezimTreninga rezim;
    ArrayList<StavkaRezimaTreninga> stavke;
    
    /**
     * Creates new form UnesiStavku
     */
    public UnesiStavku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        stavke = new ArrayList<>();
        Session.getInstance().setOtvoriFormu(true);
        initComponents();
        setUpCb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMesec = new javax.swing.JComboBox<>();
        panelHidden = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbVrsteTreninga = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNazivStavke = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnUnesiStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        btnSacuvajRezim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mesec");

        jLabel2.setText("Opis");

        cbMesec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Stavka Rezima");

        cbVrsteTreninga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Vrsta Treninga");

        jLabel6.setText("Naziv Stavke");

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        btnUnesiStavku.setText("Unesi Stavku");
        btnUnesiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHiddenLayout = new javax.swing.GroupLayout(panelHidden);
        panelHidden.setLayout(panelHiddenLayout);
        panelHiddenLayout.setHorizontalGroup(
            panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHiddenLayout.createSequentialGroup()
                .addGroup(panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHiddenLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHiddenLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVrsteTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNazivStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(panelHiddenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUnesiStavku)
                .addGap(57, 57, 57))
        );
        panelHiddenLayout.setVerticalGroup(
            panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHiddenLayout.createSequentialGroup()
                .addGroup(panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHiddenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(panelHiddenLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnUnesiStavku)))
                .addGap(12, 12, 12)
                .addGroup(panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHiddenLayout.createSequentialGroup()
                        .addGroup(panelHiddenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbVrsteTreninga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(txtNazivStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        jScrollPane1.setViewportView(txtOpis);

        btnSacuvajRezim.setText("Sacuvaj Rezim");
        btnSacuvajRezim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajRezimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMesec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(panelHidden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSacuvajRezim)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(panelHidden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacuvajRezim)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiStavkuActionPerformed
        if(!setujStavku()) {
            return;
        }
        
    }//GEN-LAST:event_btnUnesiStavkuActionPerformed

    private void btnSacuvajRezimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajRezimActionPerformed
        if(!setujRezim()){
            return;
        }
        try {
            rezim.setStavke(stavke);
            Controler.getInstance().sacuvajRezim(rezim);
            JOptionPane.showMessageDialog(null, "Sistem je zapamtio rezim.");
//            this.dispose();
            Object[] options = {"Da", "Ne"};

            if (JOptionPane.showOptionDialog(null, "Da li zelite da unesete novi rezim?", "Novi rezim",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                    null, options, options[0]) == 0) {
                UnesiStavku lup = new UnesiStavku(null, true);
                this.dispose();
                lup.setVisible(true);
            } else {
                this.dispose();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da zapamti rezim.");
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne može da zapamti rezim.");
        }
        
    }//GEN-LAST:event_btnSacuvajRezimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnesiStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnesiStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnesiStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnesiStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnesiStavku dialog = new UnesiStavku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajRezim;
    private javax.swing.JButton btnUnesiStavku;
    private javax.swing.JComboBox<String> cbMesec;
    private javax.swing.JComboBox<Object> cbVrsteTreninga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelHidden;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtNazivStavke;
    private javax.swing.JTextArea txtOpis;
    // End of variables declaration//GEN-END:variables

    private void setUpCb() {
        cbMesec.removeAllItems();
        cbMesec.addItem("Januar");
        cbMesec.addItem("Februar");
        cbMesec.addItem("Mart");
        cbMesec.addItem("April");
        cbMesec.addItem("Jun");
        cbMesec.addItem("Jul");
        cbMesec.addItem("Avgust");
        cbMesec.addItem("Septembar");
        cbMesec.addItem("Oktobar");
        cbMesec.addItem("Novembar");
        cbMesec.addItem("Decembar");
        
        
        cbVrsteTreninga.removeAllItems();
        try {
            ArrayList<VrstaTreninga> vrste = Controler.getInstance().vratiVrste();
            for (VrstaTreninga vrstaTreninga : vrste) {
                cbVrsteTreninga.addItem(vrstaTreninga);
            }
        } catch (Exception ex) {
            Logger.getLogger(UnosKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        TableModelStavke t = new TableModelStavke();
        tblStavke.setModel(t);
        
    }

    private boolean setujStavku() {
        if (
                txtNazivStavke.getText().isEmpty() 
                
                
        ){ 
            JOptionPane.showMessageDialog(null, "Popunite sva polja!");
            return false;
        }
        
        StavkaRezimaTreninga s = new StavkaRezimaTreninga(1, null, txtNazivStavke.getText(), Session.getInstance().getCurrentUser(), (VrstaTreninga) cbVrsteTreninga.getSelectedItem());
        stavke.add(s);
        TableModelStavke tms = (TableModelStavke) tblStavke.getModel();
        tms.dodajStavku(s);
        return true;
        } 

    private boolean setujRezim() {
        if (
                txtOpis.getText().isEmpty() 
                
                
        ){ 
            JOptionPane.showMessageDialog(null, "Popunite sva polja!");
            return false;
        }
        rezim = new RezimTreninga(1, txtOpis.getText(), (String) cbMesec.getSelectedItem());
        
        
        return true;
    }
}
